title: AutoFlex Documentation
description: The documentaion, that's it
theme: just-the-docs

url: "https://lzyeil.github.io"
baseurl: "/AutoFlex"
search_enabled: true

footer: Â© 2025 [Zhiyuan Li]



